### ISSUE TITLE
[Bug] ipv6+surge 订阅出现 Internal Server Error

### ISSUE THREAD

**Issue by KiriKira** [vvbbnn00/WARP-Clash-API#106]
**复现步骤**
请提供复现bug所需的具体步骤，例如：
1.  使用docker hub 的 latest 镜像运行
2. 使用订阅链接 https://domain/api/surge？best=true&randomName=false&proxyFormat=full&ipv6=true
3. 浏览器中出现 Internal Server Error

服务端 docker log：
`2024-02-29 02:09:37,535 - ERROR - Exception on /api/surge [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/web_service.py", line 89, in decoratedFunction
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/services/web_service.py", line 49, in decoratedFunction
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/services/web_service.py", line 220, in httpSubscription
    file_data = generateSurgeSubFile(account,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/subscription.py", line 240, in generateSurgeSubFile
    country = GEOIP.lookup(ip)
              ^^^^^^^^^^^^^^^^
  File "/app/utils/geoip.py", line 43, in lookup
    result = self.db.get(ip)
             ^^^^^^^^^^^^^^^
ValueError: '[2606:4700:d1::90a5:163f:7848:adf4]' does not appear to be an IPv4 or IPv6 address.`

**Comment by KiriKira** [comment]
![image](https://github.com/vvbbnn00/WARP-Clash-API/assets/32393884/3c488bd8-14cf-43bd-95e8-20c0ae7e972b)
试了一下不报错了,但看了一下配置文件surge订阅即使使用了ipv6=true依然给的是ipv4的endpoint? @vvbbnn00

**Comment by vvbbnn00** [comment]
@KiriKira 
使用的是这个订阅链接吗：https://domain/api/surge?best=true&randomName=false&proxyFormat=full&ipv6=true

**Comment by KiriKira** [comment]
是的,但我又试了一下浏览器下载下的配置文件没问题了,这个订阅是给 Android 上的 surfboard 用的,不知道是否因为缓存原因使用randomName=false 怎么更新都是 ipv4,使用 randomName=true 才能更新到 ipv6 的,初步判断是客户端的问题.
另外现在即使导入了 surfboard 似乎依然不能用 ipv6 订阅里的节点..
clash 订阅在 Hiddify 上测试是可用的,不过在同样支持 clash 订阅的 NekoboxforAndroid 上似乎又识别不出节点...暂时先不管他们吧

**Comment by shiquda** [comment]
在 Android 上使用 Clash for Android 也不能订阅，显示`proxy 0: unsupport proxy type: wireguard`
