### ISSUE TITLE
[Bug] Unable to start docker container

### ISSUE THREAD

**Issue by Arpit-Khandelwal** [vvbbnn00/WARP-Clash-API#131]
**To quickly locate the issue and reduce unnecessary trouble, please check if a
related issue already exists before creating a new one. Thank you!**

**📜 Checklist**

- [x] I understand that the current issue mainly handles `bugs` and
  accepts `feature requests`. Other types of issues (such as operational,
  configuration issues, client issues, etc.) should be posted
  in [discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions),
  otherwise, the issue may be closed.
- [x] I confirm that this is a bug caused by this project, and not due to
  Cloudflare WARP's own service limitations, client incompatibility, or other
  reasons (if unsure, please also post
  in [discussions](https://github.com/vvbbnn00/WARP-Clash-API/discussions)).
- [x] I have verified that this bug has not been mentioned in other issues.

**Bug Description**

Please describe the bug clearly and specifically, including the observed
abnormal behavior and the expected behavior.
Error while running docker container:
2024-03-06 09:49:02 Traceback (most recent call last):
2024-03-06 09:49:02   File "/app/app.py", line 94, in <module>
2024-03-06 09:49:02     main()
2024-03-06 09:49:02   File "/app/app.py", line 70, in main
2024-03-06 09:49:02     from services.web_service import createApp
2024-03-06 09:49:02   File "/app/services/web_service.py", line 27, in <module>
2024-03-06 09:49:02     from services.subscription import generateClashSubFile, generateWireguardSubFile, generateSurgeSubFile, \
2024-03-06 09:49:02   File "/app/services/subscription.py", line 37, in <module>
2024-03-06 09:49:02     CF_CONFIG = json.load(open("./config/cf-config.json", "r", encoding="utf8"))
2024-03-06 09:49:02                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-06 09:49:02 FileNotFoundError: [Errno 2] No such file or directory: './config/cf-config.json'
2024-03-06 09:49:02 /usr/local/lib/python3.11/site-packages/tzlocal/unix.py:193: UserWarning: Can not find any timezone configuration, defaulting to UTC.
2024-03-06 09:49:02   warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2024-03-06 09:49:02 2024-03-06 04:19:02,295 - INFO - Start scheduler.
2024-03-06 09:49:02 2024-03-06 04:19:02,295 - INFO - DO_GET_WARP_DATA is True, will fetch WARP data per 18 seconds.
2024-03-06 09:49:02 2024-03-06 04:19:02,295 - INFO - Start save account job, will update account info per 120 seconds.

I can verify the bind mounts are correct and cf-config.json exists in required path.

**Steps to Reproduce**

Please provide specific steps to reproduce the bug, such as:

1. Execute the command `docker-compose up -d`
2. Check container status and logs

**Expected Behavior**

Container should start running.

**Screenshots**

If applicable, please attach relevant screenshots.

**Environment Information**

Should not matter as this is a docker issue

Please accurately fill in the relevant information. If it is a server-side
issue, please provide server environment information:

- Device Model: [e.g. iPhone13/Cloud Server]

- System Version: [e.g. iOS15.1/Windows 10]

- Software Name: [e.g. ShadowRocket]

- Software Version: [e.g. v2.2.45 (2171)]

- Subscription Type: [e.g. Auto Detect/Clash/ShadowRocket/Surge/...]

- `Commit Hash` [of the project when the issue
  occurred]: [fdb97f1a61ac5deb0db8f012c59d8050c9587e6]](https://github.com/vvbbnn00/WARP-Clash-API/commit/074492624817ece441424a791f3098ae8321f435)

**Additional Information**

If there is any additional information (such as runtime logs, response data,
etc.) that can help diagnose the issue, please add it here. Be mindful of
protecting personal privacy and do not disclose sensitive information (including
but not limited to: IP address, LicenseKey, PrivateKey, SECRET_KEY).

**Comment by vvbbnn00** [comment]
Hello, thank you for your feedback. However, after trying, I seem unable to reproduce the issue on my computer. 
Could you please provide your `docker-compose.yaml` file (without `SECRET_KEY`)? 
If possible, could you also try running `ls /app/config/ -la` and `whoami` inside your Docker instance and provide a screenshot? Thank you.

**Comment by Arpit-Khandelwal** [comment]
fixed, trivial configuration issue, thanks!
