### ISSUE TITLE
[Bug] 无法注册账号，程序报错了。

### ISSUE THREAD

**Issue by chenxinxing** [vvbbnn00/WARP-Clash-API#228]
ERROR:root:Failed to load account from file: [Errno 2] No such file or directory: 'account/account.json'
2024-08-17 00:28:34,970 - INFO - No account found, register a new one
INFO:app_background:No account found, register a new one
ERROR:apscheduler.executors.default:Job "doAddDataTaskOnce (trigger: interval[0:00:18], next run at: 2024-08-17 00:28:52 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/tasks.py", line 39, in doAddDataTaskOnce
    account = getCurrentAccount(logger)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/common.py", line 38, in getCurrentAccount
    account = register(pubkey, privkey)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/services/cloudflare.py", line 111, in register
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.cloudflareclient.com/v0i2308311933/reg

**Comment by jiongjiongJOJO** [comment]
+1

**Comment by Goorwl** [comment]
+1，无法生成 account.json 文件。

**Comment by superHao2000** [comment]
+1

**Comment by bilibiliworld** [comment]
+1

**Comment by devick** [comment]
+1

**Comment by ans0600** [comment]
+1

**Comment by xubiaolin** [comment]
+1

**Comment by chentanwan** [comment]
+1

**Comment by leftchest** [comment]
+1

**Comment by RogerChen2005** [comment]
+1

**Comment by xia0sheng** [comment]
同样的问题，不能注册账号了

**Comment by 872659446** [comment]
+1
